### ISSUE TITLE
pip install not working

### ISSUE THREAD

**Issue by up2l8** [thefab/restful-distributed-lock-manager#2]
File "/home/emiller/projects/lock_server/python/build/rdlm/setup.py", line 19, in <module>

```
with open('pip-requirements.txt') as reqs:
```
## IOError: [Errno 2] No such file or directory: 'pip-requirements.txt'

I'm not intimately familiar with setup.py but I think you might need to specity pip-requirements.txt to the packger.

This is on a python2.7 virtualenv if that matters.

**Comment by thefab** [comment]
ok, I reproduce this in a p27 virtualenv

let's fix it

**Comment by thefab** [comment]
fixed in 0.4.2 (just released), thanks

clean your "build" virtualenv subdir before "pip install rdlm"
